chore!: Normalize repository, dropping node <10.13 support
gulpjs/now-and-later pull request #18
Opened 2021-12-12 09:31 UTC by sttk

This PR updates this project:

- Updates dependency versions
- Introduces GitHub Actions
- Adds, changes and deletes some project files

2022-01-10 01:01 UTC, phated requested changes
Just a couple things

2022-01-10 01:01 UTC, phated commented on package.json
>      "async",
Can you also complete #13 by adding:
```suggestion
    "async",
    "parallel",
    "series",
    "each",
```

2022-02-06 11:35 UTC, sttk commented
@phated I've commited your suggestions.

2022-06-25 00:51 UTC, phated commented on LICENSE
> +Copyright (c) 2014, 2021 Blaine Bublitz <blaine.bublitz@gmail.com> and Eric Schoffstall <yo@contra.io>
```suggestion
Copyright (c) 2014, 2021-2022 Blaine Bublitz <blaine.bublitz@gmail.com> and Eric Schoffstall <yo@contra.io>
```

2022-06-25 00:52 UTC, phated approved these changes
Looks great! Thanks @sttk 🍻

2022-06-25 00:52 UTC, merged